### ISSUE TITLE
XML Support?

### ISSUE THREAD

**Issue by vinniefalco** [copperspice/doxypress#24]
How is the XML support on doxypress? I've had a migraine lasting 2+ years from Doxygen's XML output.

**Comment by agserm** [comment]
We have done considerable work to improve the XML output for DoxyPress. Using the clang frontend for parsing (not a capability Doxygen has) although it is slower will also yield more accurate output since we can do a better job interpreting the semantics of the code.

Can you tell us some of the problems you are currently having? Better yet, do you have some test cases which illustrate the issues? We are happy to work with you and see if DoxyPress can alleviate some of your migraines.

**Comment by vinniefalco** [comment]
I guess I have to just try it, my xsl transform has workarounds for some weird Doxygen XML output. For example Doxygen emits `<type>class Allocator</type>` in one case but `<type>class</type><declname>Allocator</declname>` in another.

**Comment by agserm** [comment]
If there are any remaining issues, please reopen with details.
