### ISSUE TITLE
OSX is missing from downloads?

### ISSUE THREAD

**Issue by nrkramer** [copperspice/doxypress#30]
I don't see osx listed as a download option here:
https://download.copperspice.com/doxypress/binary/

**Comment by agserm** [comment]
Thanks for bringing this to our attention. We pulled the OS X build of DoxyPress 1.3.5 because there was an RPATH issue with our legacy Autotools build system. We have just re-posted a binary version from February 2019. The CMake files for CopperSpice and DoxyPress have been modernized, and the Autotools build system has been dropped. These changes have been committed to github, and will be part of our next release in November.
