### ISSUE TITLE
Are East Asian languages supported as input file encodings?

### ISSUE THREAD

**Issue by udaken** [copperspice/doxypress#48]
I have specified `Shift-JIS` for the input file language in the project file. (just like doxygen).

```json
"input-encoding": "Shift-JIS",
```

When I run doxypress, I get corrupted documents and the following error

> Error: Unsupported character encoding: 'Shift-JIS'

**Comment by udaken** [comment]
[Qt requires a static plugin](https://doc.qt.io/archives/qt-4.8/plugins-howto.html) to use East Asian languages (cn/jp/kr/tw), but Doxypress does not seem to have one built in.
Am I thinking right?

**Comment by bgeller** [comment]
East Asian languages are fully supported in our CopperSpice QString classes using the UTF-8 encoding. This is the preferred encoding for all languages and most of the Internet.  We understand you may have files in a legacy encoding.  Have you considered upgrading to UTF-8 for your documentation and source code. If so, we can give you some ideas about how to do this.   

Shift-JIS is a different encoding unique to Japan. The way they support this encoding is by using a Text Codec to convert back and forth between Shift-JIS and Unicode. It was added to a plugin since the size of the conversion tables are extremely large.  

Adding this plugin is something we could consider however it is not a high priority at this time since none of the clients on our paid support subscription have requested this feature. 

Barbara

**Comment by agserm** [comment]
We're looking forward to your changes to CopperSpice and DoxyPress. Please feel free to submit a pull request and we will be happy to maintain this feature for you.
